services:
  backend:
    build: .
    container_name: plant-backend
    restart: always
    env_file: .env
    expose:
      - "8000"
    networks:
      - db
      - mosquitto_default
      - web

networks:
  db:
    external: true
  mosquitto_default:
    external: true
  web:
    external: true
