version: "3.9"
services:
  backend:
    build: .
    container_name: plant-backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - db
      - mosquitto_default

networks:
  db:
    external: true
  mosquitto_default:
    external: true
